### ISSUE TITLE
Responsibility

### ISSUE THREAD

**Issue by gavsideas** [ambianic/ambianic-docs#4]
Ambianic does not currently operate within a trusted third party network for installation and setup purposes. The Ambianic product is currently a standalone open sourced asset and no liability can be assumed for any decision taken from an individual or group seeking to utilise its benefits. 

Nonetheless, potential and actual users of the system, both direct and indirect, could bear in mind the following advice from Ambianic:

1. Conduct proper research on the utility of the product
2. Set clear goals for product functionality 
3. Try to understand the product's benefits and limitations
4. In the event of uncertainty please use professional level skills for installation and system setup projects
5. Beware of any 'too good to be true' offers from marketeers offering services that relate to this product

Ambianic has been designed to enable a do-it-yourself project although it is recognised that one person's "easy" level of technical expertise is another person's "headache". For anyone attempting their own independent installation project a certain level of knowledge relating to computer software and hardware is assumed as necessary. 

Ambianic is currently an open source asset offered in the spirit of beneficial assistance to help those in need or the families and / or those close to those in need. Any use of Ambianic is done so entirely at the risk of the user/s or user/s' representatives (expressed or deemed) and no responsibility for any adverse consequences through system usage can be assumed by Ambianic.

**Comment by ivelin** [comment]
Thank you @gavsideas 

This issue is closed by #5
